from datetime import datetime
from typing import Protocol
from uuid import UUID

from luxtj.contexts.identity.domain.permission import Permission
from luxtj.contexts.identity.domain.role import Role
from luxtj.contexts.identity.domain.user import User
from luxtj.shared_kernel.application.pagination import PaginationMeta


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...
    async def save(self, user: User) -> None: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_password_reset_token_hash(self, token_hash: str) -> User | None: ...
    async def list_admin_users(
        self, *, page: int, page_size: int
    ) -> tuple[list[User], PaginationMeta]: ...
    async def count_by_role_id(self, role_id: UUID) -> int: ...


class RoleRepository(Protocol):
    async def add(self, role: Role) -> None: ...
    async def save(self, role: Role) -> None: ...
    async def get_by_id(self, role_id: UUID) -> Role | None: ...
    async def get_by_name(self, name: str) -> Role | None: ...
    async def list_roles(
        self, *, page: int, page_size: int
    ) -> tuple[list[Role], PaginationMeta]: ...


class PermissionRepository(Protocol):
    async def upsert_many(self, permissions: list[Permission]) -> None: ...
    async def list_all(self) -> list[Permission]: ...
    async def get_by_codes(self, codes: set[str]) -> list[Permission]: ...


class Clock(Protocol):
    def utcnow(self) -> datetime: ...


class IdentityTokenIssuer(Protocol):
    async def issue_pair(
        self,
        *,
        user: User,
        permission_codes: list[str],
    ) -> tuple[str, str, int, int]: ...
