from typing import Protocol

from luxtj.contexts.currency.domain.entities import ActiveCurrency, CurrencyMeta


class ActiveCurrencyRepository(Protocol):
    async def list_active_codes(self) -> list[str]: ...

    async def is_active(self, currency_code: str) -> bool: ...

    async def get_by_code(self, currency_code: str) -> ActiveCurrency | None: ...

    async def activate(self, currency_code: str) -> ActiveCurrency: ...

    async def deactivate(self, currency_code: str) -> bool: ...

    async def list_currency_metadata(self) -> list[CurrencyMeta]: ...

    async def ensure_currency_catalog(self, catalog: list[CurrencyMeta]) -> None: ...


class FxRateProvider(Protocol):
    def fetch_rates(self, pairs: list[tuple[str, str]]) -> list[dict[str, str | float | None]]: ...
