"""add action centre

Revision ID: b0682c3db2c7
Revises: 4e3eebad732e
Create Date: 2026-06-10 12:38:22.894311+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0682c3db2c7"
down_revision: str | None = "4e3eebad732e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_centre_items",
        sa.Column("workflow", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("workflow", "entity_id"),
    )
    op.create_index(
        op.f("ix_action_centre_items_status"), "action_centre_items", ["status"], unique=False
    )
    op.create_table(
        "action_centre_outbox_cursor",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("last_processed_outbox_id", sa.String(length=36), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("action_centre_outbox_cursor")
    op.drop_index(op.f("ix_action_centre_items_status"), table_name="action_centre_items")
    op.drop_table("action_centre_items")
    # ### end Alembic commands ###
