"""waitlist addition

Revision ID: 4e3eebad732e
Revises: d4e5f6a7b8c9
Create Date: 2026-06-08 04:24:10.538410+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e3eebad732e'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition_waitlist_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('referral_code', sa.String(length=128), nullable=True),
    sa.Column('acquisition_context', sa.JSON(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acquisition_waitlist_entries_email'), 'acquisition_waitlist_entries', ['email'], unique=True)
    op.drop_index(op.f('ix_action_centre_items_workflow_status'), table_name='action_centre_items')
    op.drop_table('action_centre_items')
    op.drop_table('action_centre_outbox_cursor')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_marketing_offers_status'), table_name='marketing_offers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_marketing_offers_status'), 'marketing_offers', ['status'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_per_night', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hotels_pkey'))
    )
    op.create_table('action_centre_outbox_cursor',
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('last_processed_outbox_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('action_centre_outbox_cursor_pkey'))
    )
    op.create_table('action_centre_items',
    sa.Column('workflow', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workflow', 'entity_id', name=op.f('action_centre_items_pkey'))
    )
    op.create_index(op.f('ix_action_centre_items_workflow_status'), 'action_centre_items', ['workflow', 'status'], unique=False)
    op.drop_index(op.f('ix_acquisition_waitlist_entries_email'), table_name='acquisition_waitlist_entries')
    op.drop_table('acquisition_waitlist_entries')
    # ### end Alembic commands ###
