services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    image: luxtj_be:dev
    container_name: luxtj_be_api
    env_file:
      - ../.dev.env
    ports:
      - "8000:8000"
    volumes:
      # Hot-reload: mount source code into the container
      - ../src:/app/src:ro
    restart: unless-stopped
    
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
